# This workflow will generate the README.md
name: Go

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.2'

    - name: Tidy
      run: go mod tidy

    - name: Generate README.md
      run: ./bin/gen_readme.bash

    - name: Commit & Push
      continue-on-error: true
      run: |
        git config --global user.email "auto@swiss"
        git config --global user.name "Git Hub Action go.yml"
        git add README.md
        git commit -m "ran ./bin/gen_readme.bash"
        git push origin main
